### PR TITLE
Awaits review

### PR DESCRIPTION
**Pull request by ignatius22**
-- extra "/" was removed
-- stickler issues fixed

### CODE REVIEW

**Comment by thsvr** [comment]
### **STATUS: CHANGES REQUESTED** :bulb: :bulb: 

Hi @ignatius22 :smile: :smile: 

**You have been doing a great job and you are almost there** :muscle: 
Below, there are few changes required, can you please them carefully, do the necessary fixes and then submit for another code review?

:v: As mentioned before by the TSEs, you need to fix ALL the stickler errors before submitting your project for a code review. Can you please fix them? 
:bulb: :bulb: TIPS: You can install any code formatter, such as [Prettier-code formatter](https://prettier.io/) and it will fix many errors automatically for you. :bulb: :bulb: The remaining ones you have to check and fix by yourself. :smile_cat:  

:v: As recommended by Daniel(TSE), can you please fix the readme? You need to update the live version and edit some sections as ''getting started and set up'' would be great.

:v: Why are you working alone in this project?

:v: Can you please use the same pull request for each project? After a code review, if you have to fix something, you have to use the same pull request for the next review.





If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)


**Happy coding and good luck on the next review** :muscle: 

_Project reviewed by Thaís Vieira (TSE)_

**Comment by ignatius22** [comment]
My coding partner is away, so I reported the issue to student success, and
they said I should work alone.

**Comment by uryelah** [comment]
Hello **Iggy Sani**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all good job fixing the Stickler issues, you did really well with the overall positioning on the page! 🌟**

There are still some required checks you need to fulfill in order to continue to the next project, so hang in there! 💪

---------     

## Required Changes 🏗 👷‍♀ 

- [x] Make sure there are no errors or warnings in your[ HTML validation.](https://validator.w3.org/nu)

- [x] Remember to modify the links, `<a>`, color so it's the same shade of blue as the [original page.](https://accounts.intuit.com/signup.html)

- [x] Make sure the labels and form text have the same `font-weight` as the original page if that's an issue with the font you are using change to a similar font.

Compare your page and the original one bellow, check for the differences in styling specially in color:

Screenshot_2020-04-13 Mint Clone
Screenshot_2020-04-13 Intuit Accounts - Sign Up

------

- [x]  Make sure the logo is not the same image as the items under it. Each should be its own image, Check the requirements below and make sure you fulfill all of them:
Screenshot_2020-04-13 dist html_css html_forms md · master · Microverse guides tse code_review code_review_guidelines

---- 

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by ignatius22** [comment]
html got validated
labels and form text now have the same font-weight
the link tag got modified
added separate image for the icons and header

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS @ignatius22  👏👏👏

This project meets the requirements for approval.

However, in subsequent projects kindly avoid creating a new pull request after you've received a review. Simply make the changes requested on the same branch and submit the same pull request link for re-review.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Pull request closed without merging**
